<?php
	// all
	define('LOGO', '../public/images/RBV_logo_another.svg');
	define('TOP_LOGO', '../public/images/RBV_logo_white&red.svg');
	// define('WHITE_BG_LOGO', '../public/images/RBV_logo_normal.png');
	define('WHITE_LOGO', '../public/images/RBV_logo_white.svg');
	define('BOOKING_PHONE_NUMBER', '037-824877');
	define('BOOKING_FAX_NUMBER', '037-824878');
	define('BOOKING_MOBILE_NUMBER', '0937-824-877');
	define('BOOKING_EMAIL', 'service@rbvillas.com.tw');
	define('BTN_BOOKING', 'Book Now');
	define('BTN_CLOSE_IMG', '../public/images/btn_menu_close.svg');
	define('COPYRIGHT', 'Copyright © Red Brick Villas designed by');
	define('ADDRESS', 'No.32-3, Lijinguan, Nanzhuang Village, Nanzhuang Township, Miaoli County, Taiwan');
	define('COMMON_TEXT_1', 'Learn More');
	define('COMMON_TEXT_2', 'More Attractions');
	define('COMMON_TEXT_3', 'Read more');
	define('CHECK_IN', 'Check In');
	define('CHECK_OUT', 'Check Out');
	define('ROOOMS', 'Rooms');
	//burger_menu
	define('BURGUR_MENU_ICON_1', '../public/images/illu01_aboutus_white.svg');
	define('BURGUR_MENU_ICON_2', '../public/images/illu01_news_white.svg');
	define('BURGUR_MENU_ICON_3', '../public/images/illu03_rooms_white.svg');
	define('BURGUR_MENU_ICON_4', '../public/images/illu04_foods_white.svg');
	define('BURGUR_MENU_ICON_5', '../public/images/illu03_hotpots_white.svg');
	define('BURGUR_MENU_ICON_6', '../public/images/illu05_location_white.svg');
	define('BURGUR_MENU_ICON_7', '../public/images/illu07_contactus_white.svg');
	define('BURGUR_MENU_ICON_8', '../public/images/illu08_atm_white.svg');
	define('BURGUR_MENU_ICON_9', '../public/images/btn_footer_mail_white.svg');
	define('BURGUR_MENU_ICON_10', '../public/images/btn_footer_telephone_white.svg');
	define('BURGUR_MENU_ICON_11', '../public/images/btn_footer_printer_white.svg');
	define('BURGUR_MENU_ICON_12', '../public/images/btn_footer_cellphone_white.svg');
	define('BURGUR_MENU_ICON_13', '../public/images/btn_facebook_white.svg');
	define('BURGUR_MENU_ICON_14', '../public/images/btn_youtube_white.svg');
	define('BURGUR_MENU_TEXT_1', 'About Us');
	define('BURGUR_MENU_TEXT_2', 'News');
	define('BURGUR_MENU_TEXT_3', 'Rooms');
	define('BURGUR_MENU_TEXT_4', 'Food');
	define('BURGUR_MENU_TEXT_5', 'Attractions');
	define('BURGUR_MENU_TEXT_6', 'Location');
	define('BURGUR_MENU_TEXT_7', 'Contact Us');
	define('BURGUR_MENU_TEXT_8', 'Deposit Info');
	define('BURGUR_MENU_FB_LINK', 'https://www.facebook.com/%E7%B4%85%E7%A3%9A%E5%B1%8B%E7%89%B9%E8%89%B2%E6%B0%91%E5%AE%BF-557971720914982/');
	define('BURGUR_MENU_YOUTUBE_LINK', 'https://www.youtube.com/playlist?list=PLTg3nYLJvTjKzvLYwEY5FUFaSgyxqkha8');
	define('DOIT_FOOTER_LOGO', '../public/images/doit_logo.svg');
	//footer
	define('FOOTER_TEXT_1', '紅磚屋特色民宿/Red Brick Villas');
	define('FOOTER_IMG_1', '../public/images/btn_footer_map.svg');
	define('FOOTER_IMG_2', '../public/images/btn_footer_mail_black.svg');
	define('FOOTER_IMG_3', '../public/images/btn_footer_telephone_black.svg');
	define('FOOTER_IMG_4', '../public/images/btn_footer_printer_black.svg');
	define('FOOTER_IMG_5', '../public/images/btn_footer_cellphone.svg');
	define('FOOTER_IMG_6', '../public/images/btn_facebook_black.svg');
	define('FOOTER_IMG_7', '../public/images/btn_youtube_black.svg');
	define('FOOTER_IMG_8', '../public/images/logo_footer_01.svg');
	define('FOOTER_IMG_9', '../public/images/logo_footer_02.jpg');
	define('FOOTER_IMG_10', '../public/images/logo_footer_03.svg');
	define('FOOTER_IMG_11', '../public/images/logo_footer_04.jpg');
	//home
	define('HOME_WEB_TITLE', 'Home');
	define('HOME_MAIN_TITLE', 'home');
	define('HOME_ROW_TITLE_1', '浪漫台三線計劃-推展慢食、漫遊、慢活的休閒產業');
	define('HOME_ROW_TEXT_1', '蔡英文總統落實政見「浪漫台三線」在紅磚屋召開產業界座談會。');
	define('HOME_ROW_TITLE_2', '紅磚屋空拍美景影片欣賞');
	define('HOME_ROW_TEXT_2', '2016年4月2日-住客分享四軸空拍機空拍紅磚屋特色民宿美景。');
	define('HOME_ROW_TITLE_3', '親土、親民、親夢想');
	define('HOME_ROW_TEXT_3', '親土、親民、親夢想-鐘年誼在紅磚屋的歲月。');
	define('HOME_BTN_MORE_ICON', '../public/images/btn_more_normal.svg');
	define('HOME_BTN_MORE_TEXT', '更多消息快報...');
	define('HOME_TOPIC_TITLE', '“Here is YOUR HOME in Nanzhuang”');
	define('HOME_TOPIC_TEXT_1', 'Red Brick Villas (RBV) is located in Nanzhuang and surrounded by mountains.');
	define('HOME_TOPIC_TEXT_2', 'Staying in RBV is the best way to enjoy Taiwan’s countryside.');
	define('HOME_TOPIC_TEXT_3', 'We welcome you to experience the beauty of Nanzhuang!');
	define('HOME_TOPIC_IMG', '../public/images/icon_brickline_normal.svg');
	define('HOME_PHOTO_1', '../public/images/home/pic01_1.jpg');
	define('HOME_PHOTO_2', '../public/images/home/pic01_2.jpg');
	define('HOME_PHOTO_3', '../public/images/home/pic01_3.jpg');
	define('HOME_PHOTO_4', '../public/images/home/pic01_4.jpg');
	define('HOME_TEXT_1', 'Attractions');
	define('HOME_SPOT_NAME_1', 'Nanzhuang Old Street / Old Post Office / Osmanthus Alley');
	define('HOME_SPOT_IMG_1', '../public/images/spots/spot_03.jpg');
	define('HOME_SPOT_NAME_2', 'Xiangtian Lake ');
	define('HOME_SPOT_IMG_2', '../public/images/spots/spot_02.jpg');
	define('HOME_SPOT_NAME_3', 'Penglai River Nature Park');
	define('HOME_SPOT_IMG_3', '../public/images/spots/spot_08.jpg');
	define('HOME_CENTER_IMG', '../public/images/home/banner_typographic.png');
	// about us
	define('ABOUT_US_WEB_TITLE', 'About Us');
	define('ABOUT_US_TOP_BG', '../public/images/bannerpic_01B_about.jpg');
	define('ABOUT_US_M_TOP_BG', '../public/images/bannerpic_01S_about.jpg');
	define('ABOUT_US_MAIN_TITLE', 'about_us');
 	define('ABOUT_US_MAIN_TITLE_ICON', '../public/images/illu01_aboutus_color.svg');
 	define('ABOUT_US_MAIN_TITLE_IMG', '../public/images/title02_aboutus.svg');
 	define('ABOUT_US_TEXT_1', "Red Brick Villa (RBV) is located at Lijinguan, Nanzhuang Township, Miaoli County. RBV is a unique B&B that was built with red plain bricks and grey roofing tiles. The colors of the buildings match the natural environment very well. RBV has a spectacular mountain view and a charming garden. It's a good place for you and your family or friends to enjoy a weekend getaway trip. Staying in RBV will definitely satisfied your dream of experiencing life in Taiwan's beautiful countryside.");
 	define('ABOUT_US_INTRO_IMG_1', '../public/images/about/about_01.jpg');
 	define('ABOUT_US_INTRO_TITLE_1', 'Modern Architecture with the Flavor of the Old Days');
 	define('ABOUT_US_INTRO_TEXT_1', 'RBV is the most quality place to live in Nanzhuang. The host of RBV, Johnny Chung, is a certified architect. He designed the villas with red plain bricks. Each villas has 4-5 bedrooms and 2-3 bathrooms. The villas are also equipped with living rooms, kitchens, dining rooms, and picnic area, which are not common in other B&B. The idea of RBV is to make you feel like staying in your own home in Nanzhuang.');
 	define('ABOUT_US_INTRO_IMG_2', '../public/images/about/about_02.jpg');
 	define('ABOUT_US_INTRO_TITLE_2', 'The First Certified Featured B&B in Maioli');
 	define('ABOUT_US_INTRO_TEXT_2', 'RBV is the first certified Feature B&B in Maioli. We are qualified due to four main features: including ecosystem diversity, landscape design, architecture style and coordiation with the development of local recreational industries. We are the first Featured B&B that was approved by the Miaoli County Government.');
 	define('ABOUT_US_INTRO_IMG_3', '../public/images/about/about_03.jpg');
 	define('ABOUT_US_INTRO_TITLE_3', 'RBV Garden-Heavenly Place');
 	define('ABOUT_US_INTRO_TEXT_3', 'Come walk barefoot on our 7,000 square feet garden, where you can feel nature at your feet or have a picnic and be amazed by our scenic mountain view. The landscape of the garden is designed by our RBV hostess Debbie. We change the plants in our garden for each season and our villas is decorated with many floweers and plants to give our guest a fresh new view and experience. RBV is a place where the clouds touch the mountians and the landscape is just right, it is like a heavenly place filled with flourishing flowers.');
 	define('ABOUT_US_INTRO_IMG_4', '../public/images/about/about_04.jpg');
 	define('ABOUT_US_INTRO_TITLE_4', 'Immersed in the Naturel Environment');
 	define('ABOUT_US_INTRO_TEXT_4', 'The clean mountain spring water go straight into the pool in our garden. The fresh cool water drives you to jump in and have fun. With beautiful plants and landscape, RBV is the best place to experience the nature of Nanzhuang.');
 	define('ABOUT_US_TEXT_2', 'Gallery');
 	define('ABOUT_US_GALLERY_IMG_1', '../public/images/about/gallery/gallery_01M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_1', '../public/images/about/gallery/gallery_01D.jpg');
 	define('ABOUT_US_GALLERY_IMG_2', '../public/images/about/gallery/gallery_02M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_2', '../public/images/about/gallery/gallery_02D.jpg');
 	define('ABOUT_US_GALLERY_IMG_3', '../public/images/about/gallery/gallery_03M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_3', '../public/images/about/gallery/gallery_03D.jpg');
 	define('ABOUT_US_GALLERY_IMG_4', '../public/images/about/gallery/gallery_04M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_4', '../public/images/about/gallery/gallery_04D.jpg');
 	define('ABOUT_US_GALLERY_IMG_5', '../public/images/about/gallery/gallery_05M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_5', '../public/images/about/gallery/gallery_05D.jpg');
 	define('ABOUT_US_GALLERY_IMG_6', '../public/images/about/gallery/gallery_06M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_6', '../public/images/about/gallery/gallery_06D.jpg');
 	define('ABOUT_US_GALLERY_IMG_7', '../public/images/about/gallery/gallery_07M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_7', '../public/images/about/gallery/gallery_07D.jpg');
 	define('ABOUT_US_GALLERY_IMG_8', '../public/images/about/gallery/gallery_08M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_8', '../public/images/about/gallery/gallery_08D.jpg');
 	define('ABOUT_US_GALLERY_IMG_9', '../public/images/about/gallery/gallery_09M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_9', '../public/images/about/gallery/gallery_09D.jpg');
 	define('ABOUT_US_GALLERY_IMG_10', '../public/images/about/gallery/gallery_10M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_10', '../public/images/about/gallery/gallery_10D.jpg');
 	define('ABOUT_US_GALLERY_IMG_11', '../public/images/about/gallery/gallery_11M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_11', '../public/images/about/gallery/gallery_11D.jpg');
 	define('ABOUT_US_GALLERY_IMG_12', '../public/images/about/gallery/gallery_12M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_12', '../public/images/about/gallery/gallery_12D.jpg');
 	define('ABOUT_US_GALLERY_IMG_13', '../public/images/about/gallery/gallery_13M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_13', '../public/images/about/gallery/gallery_13D.jpg');
 	define('ABOUT_US_GALLERY_IMG_14', '../public/images/about/gallery/gallery_14M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_14', '../public/images/about/gallery/gallery_14D.jpg');
 	define('ABOUT_US_GALLERY_IMG_15', '../public/images/about/gallery/gallery_15M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_15', '../public/images/about/gallery/gallery_15D.jpg');
 	define('ABOUT_US_GALLERY_IMG_16', '../public/images/about/gallery/gallery_16M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_16', '../public/images/about/gallery/gallery_16D.jpg');
 	define('ABOUT_US_GALLERY_IMG_17', '../public/images/about/gallery/gallery_17M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_17', '../public/images/about/gallery/gallery_17D.jpg');
 	define('ABOUT_US_GALLERY_IMG_18', '../public/images/about/gallery/gallery_18M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_18', '../public/images/about/gallery/gallery_18D.jpg');
 	define('ABOUT_US_GALLERY_IMG_19', '../public/images/about/gallery/gallery_19M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_19', '../public/images/about/gallery/gallery_19D.jpg');
 	define('ABOUT_US_GALLERY_IMG_20', '../public/images/about/gallery/gallery_20M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_20', '../public/images/about/gallery/gallery_20D.jpg');
 	define('ABOUT_US_GALLERY_IMG_21', '../public/images/about/gallery/gallery_21M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_21', '../public/images/about/gallery/gallery_21D.jpg');
 	define('ABOUT_US_GALLERY_IMG_22', '../public/images/about/gallery/gallery_22M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_22', '../public/images/about/gallery/gallery_22D.jpg');
 	define('ABOUT_US_GALLERY_IMG_23', '../public/images/about/gallery/gallery_23M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_23', '../public/images/about/gallery/gallery_23D.jpg');
 	define('ABOUT_US_GALLERY_IMG_24', '../public/images/about/gallery/gallery_24M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_24', '../public/images/about/gallery/gallery_24D.jpg');
 	define('ABOUT_US_GALLERY_IMG_25', '../public/images/about/gallery/gallery_25M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_25', '../public/images/about/gallery/gallery_25D.jpg');
 	define('ABOUT_US_GALLERY_IMG_26', '../public/images/about/gallery/gallery_26M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_26', '../public/images/about/gallery/gallery_26D.jpg');
 	define('ABOUT_US_GALLERY_IMG_27', '../public/images/about/gallery/gallery_27M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_27', '../public/images/about/gallery/gallery_27D.jpg');
 	define('ABOUT_US_GALLERY_IMG_28', '../public/images/about/gallery/gallery_28M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_28', '../public/images/about/gallery/gallery_28D.jpg');
 	define('ABOUT_US_GALLERY_IMG_29', '../public/images/about/gallery/gallery_29M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_29', '../public/images/about/gallery/gallery_29D.jpg');
 	define('ABOUT_US_GALLERY_IMG_30', '../public/images/about/gallery/gallery_30M.jpg');
 	define('ABOUT_US_HD_GALLERY_IMG_30', '../public/images/about/gallery/gallery_30D.jpg');
 	define('ABOUT_US_BTN_PANORAMA_IMG', '../public/images/btn_panorama_normal.svg');
 	define('ABOUT_US_BTN_PANORAMA', 'RBV Panorama');
 	define('ABOUT_US_BTN_PANORAMA_LINK', 'https://www.google.com/maps/place/%E7%B4%85%E7%A3%9A%E5%B1%8B%E7%89%B9%E8%89%B2%E6%B0%91%E5%AE%BF/@24.5857481,120.9981095,3a,75y,303.75h,65.48t/data=!3m8!1e1!3m6!1sd3zVcDQG0J4AAAQpnS4AeA!2e0!3e2!6s%2F%2Fgeo1.ggpht.com%2Fcbk%3Fpanoid%3Dd3zVcDQG0J4AAAQpnS4AeA%26output%3Dthumbnail%26cb_client%3Dsearch.TACTILE.gps%26thumb%3D2%26w%3D129%26h%3D106%26yaw%3D338.86703%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656!4m5!3m4!1s0x0:0x9a1e624041096ae6!8m2!3d24.585571!4d120.9977129!6m1!1e1?hl=zh-TW');
 	// news
 	define('NEWS_WEB_TITLE', 'News');
 	define('NEWS_TOP_BG', '../public/images/bannerpic_02B_news.jpg');
	define('NEWS_M_TOP_BG', '../public/images/bannerpic_02S_news.jpg');
	define('NEWS_MAIN_TITLE', 'news');
 	define('NEWS_MAIN_TITLE_ICON', '../public/images/illu01_news_color.svg');
	define('NEWS_MAIN_TITLE_IMG', '../public/images/title01_news.svg');
	define('NEWS_ROW_VIDEO', '<iframe width="100%" height="100%" src="https://www.youtube.com/embed/JP3qg82U6MA" frameborder="0" allowfullscreen></iframe>');
	define('NEWS_ROW_IMG', 'http://placehold.it/500x333');
	define('NEWS_ROW_TITLE_ICON', '../public/images/icon_title_normal.svg');
	define('NEWS_ROW_TITLE_1', '古早味的新建築-紅磚屋特色民宿');
 	define('NEWS_ROW_TEXT_1', '紅磚屋特色民宿可以說是南庄最具品味的住宿點，本身即為建築師的莊主鍾年誼先生規劃設計下，六棟造型新穎的的別墅全由清水紅磚砌成，每棟各有4～5間臥房，2～3套衛浴設備，而且，一般民宿沒有的客廳、餐廳、廚房、家電設備一應俱全，讓您有如把「家」移到南庄一般，而門前的庭園綠草如茵、水池清澈，山莊備有野餐桌，您可把大餐移到屋外享用！');
 	define('NEWS_ROW_ARROW_ICON', '../public/images/icon_newarrow_up.svg');
 	// foods
 	define('FOODS_WEB_TITLE', 'Food');
 	define('FOODS_TOP_BG', '../public/images/bannerpic_04B_foods.jpg');
	define('FOODS_M_TOP_BG', '../public/images/bannerpic_04S_foods.jpg');
	define('FOODS_MAIN_TITLE', 'foods');
 	define('FOODS_MAIN_TITLE_ICON', '../public/images/illu04_foods_color.svg');
 	define('FOODS_MAIN_TITLE_IMG', '../public/images/title04_foods.svg');
	define('FOODS_IMG_1', '../public/images/foods/foods_01.jpg');
	define('FOODS_TITLE_1', 'RBV Café');
	define('FOODS_TEXT_1', 'The building of RBV Café was built with steel and bricks, which matches the structure of our Villas. The huge glass windows offer a great view of the mountains as you sit inside enjoying a cup of coffee. Sometimes you can even see birds flying through the sky or a butterfly flying around the window. RBV Café will definitely provide you a joyful afternoon time.');
	define('FOODS_IMG_2', '../public/images/foods/foods_02.jpg');
	define('FOODS_TITLE_2', 'Afternoon Tea');
	define('FOODS_TEXT_2', 'We serve a variety of freshly brewed coffee, local organic tea, and delicious waffles. You can enjoy a wonderful afternoon tea time with our tasty food and drinks. ');
	define('FOODS_IMG_3', '../public/images/foods/foods_03.jpg');
	define('FOODS_TITLE_3', 'Chinese Buffet Breakfast');
	define('FOODS_TEXT_3', 'We offer Chinese Buffet Breakfast for our guests. The vegetables we use are grown by our local farmers and we change dishes from season to season. We hope to start your morning with these freshly made foods.');
	define('FOODS_IMG_4', '../public/images/foods/foods_04.jpg');
	define('FOODS_TITLE_4', 'Local Farm Products');
	define('FOODS_TEXT_4', 'RBV Café provides some local farm products for you to purchase, which includes organic tea and Hakka style fermented tofu. They are the best souvenirs to bring home with you!');
	define('FOODS_IMG_5', '../public/images/foods/foods_06.jpg');
	define('FOODS_TITLE_5', 'Picnic Area');
	define('FOODS_TEXT_5', "There's a big picnic table in front of each villa. You can have BBQ or tea here with your friends and family.");
	define('FOODS_IMG_6', '../public/images/foods/foods_07.jpg');
	define('FOODS_TITLE_6', 'Meeting Room');
	define('FOODS_TEXT_6', 'RBV Café is also functioned as a meeting room that can be used for business meetings. With outstanding assistance and determined customer service, we will make sure that your business gathering will be one to remember.');
	// define('FOODS_IMG_7', '../public/images/foods/foods_07.jpg');
	// define('FOODS_TITLE_7', '咖啡屋會議室，兼具休閒與商務之空間');
	// define('FOODS_TEXT_7', '咖啡屋兼具餐廳、會議、教室、休閒等多功能用途。歡迎各機關團提利用咖啡屋進行課程或會議活動，在風光明媚寧靜的環境中進行討論，更容易使活動圓滿成功。');
	// location
	define('LOCATION_WEB_TITLE', 'Location');
 	define('LOCATION_TOP_BG', '../public/images/bannerpic_06B_location.jpg');
	define('LOCATION_M_TOP_BG', '../public/images/bannerpic_06S_location.jpg');
	define('LOCATION_MAIN_TITLE', 'location');
 	define('LOCATION_MAIN_TITLE_ICON', '../public/images/illu05_location_color.svg');
 	define('LOCATION_MAIN_TITLE_IMG', '../public/images/title06_location.svg');
 	define('LOCATION_TEXT_1', 'Address / No.32-3, Lijinguan, Nanzhuang Township, Miaoli County 353, Taiwan');
 	define('LOCATION_GOOGLE_ADDRESS', 'https://www.google.com.tw/maps/place/%E7%B4%85%E7%A3%9A%E5%B1%8B%E7%89%B9%E8%89%B2%E6%B0%91%E5%AE%BF/@24.585571,120.9955189,17z/data=!3m1!4b1!4m5!3m4!1s0x346851f28e6b5c29:0x9a1e624041096ae6!8m2!3d24.585571!4d120.9977129');
 	define('LOCATION_TEXT_2', 'Map of RBV and surrounding attractions.');
 	define('LOCATION_MAP', '../public/images/location/map.jpg');
 	define('LOCATION_TITLE_1', 'Driving Direction');
 	define('LOCATION_TITLE_2', 'Public Transportation');
 	define('LOCATION_WAY_TITLE_1', 'Get Off at Toufen Interchange Exit');
 	define('LOCATION_WAY_SUB_TITLE_1', '(Fastest Route to RBV)');
 	define('LOCATION_WAY_TEXT_1', 'Get on the National Highway No.1 from north → Get off at Toufen Interchange Exit (to Sanwan) → Turn Left to Miaoli County Highway No.124 → Pass Through Sanjuhu ＆ Sanwan Junior High School → Turn Left to Miaoli Line No.20 → Nangzhuang → RBV');
 	define('LOCATION_WAY_TITLE_2', 'Get off at Miaoli Interchange Exit');
 	define('LOCATION_WAY_SUB_TITLE_2', '(You can travel to Gaunguan, Dahu and Tai-An before arrving at RBV)');
 	define('LOCATION_WAY_TEXT_2', 'Get on the National Highway No.1 from south → Get off at Miaoli Interchange Exit → Take Provincial Highway Line No.6 to Gonguan & Shihtan Wenshui → Take Miaoli County Highway No.124 to Baguali & Penglai → RBV');
 	define('LOCATION_WAY_TITLE_3', 'Get off at Chulin Interchange Exit');
 	define('LOCATION_WAY_SUB_TITLE_3', "(You can travel to Beipu, Emei and Lion's Head Mountain Senic Area before arriving at RBV)");
 	define('LOCATION_WAY_TEXT_3', "Get on the National Highway No.3 - Get off at Chulin Interchange Exit - Chudong - Provincial Highway Line No. 3 - Beipu - Emei - Lion's Head Mountain Senic Area - Nanzhuangg - RBV");
 	define('LOCATION_WAY_TITLE_4', 'Take TRA to Chunan Station');
 	define('LOCATION_WAY_SUB_TITLE_4', 'Take Kou-Kuang Bus to Toufen Station');
 	define('LOCATION_WAY_TEXT_4', 'Take Miaoli Bus or Taiwan Tourist Shuttle from TRA Chunan Station or Toufen Bus Station - Toufen - Sanwan - Nanzhuang - take a Taxi to RBV');
 	define('LOCATION_WAY_IMG_1', '../public/images/logo_location_01.png');
 	define('LOCATION_WAY_IMG_2', '../public/images/logo_location_02.png');
 	// contact us
 	define('CONTACT_US_WEB_TITLE', 'Contact Us');
 	define('CONTACT_US_TOP_BG', '../public/images/bannerpic_07B_contactus.jpg');
	define('CONTACT_US_M_TOP_BG', '../public/images/bannerpic_07S_contactus.jpg');
	define('CONTACT_US_MAIN_TITLE', 'contact_us');
 	define('CONTACT_US_MAIN_TITLE_ICON', '../public/images/illu07_contactus_color.svg');
 	define('CONTACT_US_MAIN_TITLE_IMG', '../public/images/title07_contactus.svg');
 	define('CONTACT_US_TEXT_1', '地址 / ');
 	define('CONTACT_US_TEXT_2', '苗栗縣南庄鄉南江村9鄰里金館32-3號');
	define('CONTACT_US_TEXT_3', '電話 / ');
 	define('CONTACT_US_TEXT_4', '線上訂房系統 / ');
 	define('CONTACT_US_TEXT_5', 'www.ezhotel.com.tw/rbvillas');
 	define('CONTACT_US_TEXT_6', 'Dear guest, if you have any questions about your stay in RBV, our team is happy to help you. Thank you!');
 	define('CONTACT_US_TEXT_7', '傳真 / ');
 	define('CONTACT_US_TEXT_8', 'Name  (required field)');
 	define('CONTACT_US_TEXT_9', 'Phone Number');
 	define('CONTACT_US_TEXT_10', 'Mobile Phone Number  (required field)');
 	define('CONTACT_US_TEXT_11', 'E-mail Address');
 	define('CONTACT_US_TEXT_12', 'Address');
 	define('CONTACT_US_TEXT_13', 'Your Message For Us  (required field)');
 	define('CONTACT_US_TEXT_14', 'Enter Security Code');
 	define('CONTACT_US_TEXT_15', 'Send');
 	define('CONTACT_US_BTN_REFRESH', '../public/images/btn_reflash_normal.svg');
 	// spots
 	define('SPOTS_WEB_TITLE', 'Attractions');
 	define('SPOTS_TOP_BG', '../public/images/bannerpic_05B_hotspot.jpg');
	define('SPOTS_M_TOP_BG', '../public/images/bannerpic_05S_hotspot.jpg');
	define('SPOTS_MAIN_TITLE', 'spots');
 	define('SPOTS_MAIN_TITLE_ICON', '../public/images/illu03_hotpots_color.svg');
 	define('SPOTS_MAIN_TITLE_IMG', '../public/images/title05_attractions.svg');
 	define('SPOTS_TEXT_MORE', 'Learn More>');
 	define('SPOT_DETAIL_TEXT_BTN_BACK', '< Back');
 	define('SPOT_DETAIL_BTN_BACK_PATH', 'spots.php');
 	define('SPOT_DETAIL_TEXT_1', 'Location');
 	define('SPOT_DETAIL_TEXT_2', 'Address');
 	define('SPOT_DETAIL_TEXT_3', 'Phone');
 	define('SPOT_DETAIL_TEXT_4', 'Opening Hours');
 	// rooms
 	define('ROOMS_WEB_TITLE', 'Rooms');
 	define('ROOMS_TOP_BG', '../public/images/bannerpic_03B_rooms.jpg');
	define('ROOMS_M_TOP_BG', '../public/images/bannerpic_03S_rooms.jpg');
	define('ROOMS_MAIN_TITLE', 'rooms');
 	define('ROOMS_MAIN_TITLE_ICON', '../public/images/illu03_rooms_color.svg');
 	define('ROOMS_MAIN_TITLE_IMG', '../public/images/title03_rooms.svg');
 	define('ROOMS_TOPIC_PIC', '../public/images/rooms/rooms_01.jpg');
 	define('ROOMS_TOPIC_TITLE', 'Red Brick Villas- Enjoy the country lifestyle of Taiwan');
 	define('ROOMS_TOPIC_TEXT', 'RBV is a place where you can feel like at home. Each villa is equipped with a kitchen and cooking utensils so that you can make your own delicious meal. Also, we have a picnic area in front of each villa for BBQ. We want you to chill and have fun with your friends and family. If you feel like eating out, there are plenty of great Hakka restaurants nearby where you can enjoy authentic food in Nanchuang!');
 	define('ROOMS_TEXT_1', 'RBV Floor Plan');
 	define('ROOMS_TEXT_2', 'Price Table');
 	define('ROOMS_TEXT_3', 'Booking Notice');
 	define('ROOMS_TEXT_4', 'First Floor Plan');
 	define('ROOMS_TEXT_5', 'Second Floor Plan for Villas 1 & 2');
 	define('ROOMS_TEXT_6', 'Second Floor Plan for Villas 3, 5, 6 & 7');
 	define('ROOMS_TEXT_7', '(NT$)');
 	define('ROOMS_TEXT_8', '＊進房時間為當日15:00，退房時間為隔日11:00﹙逾時另收費用﹚；費用已含 10%服務費，並附贈早餐。 ＊本山莊週六假日僅接受整棟訂房，週日到週五才可單間訂房。 ＊請多利用線上訂房系統，手續快捷簡便，當日房價享9折優惠。 ＊完成匯款後請立即通知本山莊，確認後才算完成訂房手續。');
 	define('ROOMS_TEXT_9', '＊本山莊週六假日僅接受整棟訂房，週日到週五才可單間訂房。');
 	define('ROOMS_TEXT_10', '＊請多利用線上訂房系統，手續快捷簡便，當日房價享9折優惠。');
 	define('ROOMS_TEXT_11', '＊完成匯款後請立即通知本山莊，確認後才算完成訂房手續。');
 	define('ROOMS_TEXT_12', 'Deposit Info');
 	define('ROOMS_TEXT_13', '＊為維護住宿品質，恕不接受超住，訂房時請正確告知人數﹙幾大幾小﹚， 每棟限住十位，超過人數每人加收清潔費: 500元。 ＊每棟最多限加四人。如未報確實人數，本山莊有權不接受超住並拒絕辦理入住手續。 ＊本山莊不加床，加租棉被依規定收費；本山莊嚴禁帶寵物。 ＊取消訂房注意事項: ★旅客於住宿日前1日內取消訂房扣房價總金額100%。 ★旅客於住宿日前3日內取消訂房扣房價總金額50%。 ★旅客於住宿日前7日內取消訂房扣房價總金額20%。 ★旅客於住宿日前8日前(含8日)取消訂房扣房價總金額10%。 若因不可抗力因素無法進住，請於當天10:00前告知，得接受訂房延期，否則訂金沒收。');
 	define('ROOMS_TEXT_14', '＊每棟最多限加四人。如未報確實人數，本山莊有權不接受超住並拒絕辦理入住手續。');
 	define('ROOMS_TEXT_15', '＊本山莊不加床，加租棉被依規定收費；本山莊嚴禁帶寵物。');
 	define('ROOMS_TEXT_16', '＊取消訂房注意事項:');
 	define('ROOMS_TEXT_17', '★旅客於住宿日前1日內取消訂房扣房價總金額100%。');
 	define('ROOMS_TEXT_18', '★旅客於住宿日前3日內取消訂房扣房價總金額50%。');
 	define('ROOMS_TEXT_19', '★旅客於住宿日前7日內取消訂房扣房價總金額20%。');
 	define('ROOMS_TEXT_20', '★旅客於住宿日前8日前(含8日)取消訂房扣房價總金額10%。');
 	define('ROOMS_TEXT_21', '若因不可抗力因素無法進住，請於當天10:00前告知，得接受訂房延期，否則訂金沒收。');
 	define('ROOMS_PAY_INFO_TEXT_1', 'Deposit Info 1');
 	define('ROOMS_PAY_INFO_TEXT_2', 'Deposit Info 2');
 	define('ROOMS_PAY_INFO_TEXT_3', '行庫 / ');
 	define('ROOMS_PAY_INFO_TEXT_4', '戶名 / ');
 	define('ROOMS_PAY_INFO_TEXT_5', '局號 / ');
 	define('ROOMS_PAY_INFO_TEXT_6', '帳號 / ');
 	define('ROOMS_PAY_INFO_TEXT_7', 'ATM轉帳代號 / ');
 	define('ROOMS_PAY_INFO_TEXT_8', '南庄鄉農會');
 	define('ROOMS_PAY_INFO_TEXT_9', '紅磚屋開發有限公司');
 	define('ROOMS_PAY_INFO_TEXT_10', '92101010063619');
 	define('ROOMS_PAY_INFO_TEXT_11', '954');
 	define('ROOMS_PAY_INFO_TEXT_12', '頭份郵局');
 	define('ROOMS_PAY_INFO_TEXT_13', '鍾年誼');
 	define('ROOMS_PAY_INFO_TEXT_14', '029129-0');
 	define('ROOMS_PAY_INFO_TEXT_15', '007425-4');
 	define('ROOMS_PAY_INFO_TEXT_16', '700');
 	define('ROOMS_PAY_INFO_TEXT_17', 'After the remittance, please inform us by phone or E-mail to complete the reservation.');
 	define('ROOMS_PAY_INFO_TEXT_18', 'Phone：');
 	define('ROOMS_PAY_INFO_TEXT_19', '037-824877');
 	define('ROOMS_BTN_CONTACT_US', '../public/images/btn_footer_telephone_white.svg');
 	define('ROOMS_BTN_CONTACT_US_TEXT', 'Contact Us');
 	define('ROOMS_BTN_ATM', '../public/images/btn_atm_normal.svg');
 	define('ROOMS_FEE_TABLE_TEXT_1', 'Types of Room');
 	define('ROOMS_FEE_TABLE_TEXT_2', 'Original Price');
 	define('ROOMS_FEE_TABLE_TEXT_3', 'Weekday Rate (Sunday-Friday)');
 	define('ROOMS_FEE_TABLE_TEXT_4', 'Weekend/ Holiday Rate');
 	define('ROOMS_PLAN_1', '../public/images/Floor-Plan_01-1_EN.png');
 	define('ROOMS_PLAN_2', '../public/images/Floor-Plan_02-1_EN.png');
 	define('ROOMS_PLAN_3', '../public/images/Floor-Plan_03-1_EN.png');
 	define('ROOMS_BTN_PHOTO', '../public/images/btn_photo_normal.svg');
 	define('ROOMS_BTN_PHOTO_ACTIVE', '../public/images/btn_photo_press.svg');
 	define('ROOMS_PLAN_1_SPOT_1_TEXT', '野餐區');
 	define('ROOMS_PLAN_1_SPOT_1_IMG_1', 'http://placehold.it/400x250/ff00ff/fff?text=Product+Image.jpg');
 	define('ROOMS_PLAN_1_SPOT_1_HD_IMG_1', 'http://placehold.it/1600x1000/ff00ff/fff?text=Product+Image.jpg');
 	define('ROOMS_PLAN_1_SPOT_1_IMG_2', 'http://placehold.it/400x250/ffff00/fff?text=Product+Image.jpg');
 	define('ROOMS_PLAN_1_SPOT_1_HD_IMG_2', 'http://placehold.it/1600x1000/ffff00/fff?text=Product+Image.jpg');
 	define('ROOMS_PLAN_1_SPOT_1_IMG_3', 'http://placehold.it/400x250/00ffff/fff?text=Product+Image.jpg');
 	define('ROOMS_PLAN_1_SPOT_1_HD_IMG_3', 'http://placehold.it/1600x1000/00ffff/fff?text=Product+Image.jpg');
 	define('ROOMS_PLAN_1_SPOT_2_TEXT', '浴廁');
 	define('ROOMS_PLAN_1_SPOT_2_IMG_1', 'http://placehold.it/400x250/ff00ff/fff?text=Product+Image.jpg');
 	define('ROOMS_PLAN_1_SPOT_2_HD_IMG_1', 'http://placehold.it/1600x1000/ff00ff/fff?text=Product+Image.jpg');
 	define('ROOMS_PLAN_1_SPOT_2_IMG_2', 'http://placehold.it/400x250/ffff00/fff?text=Product+Image.jpg');
 	define('ROOMS_PLAN_1_SPOT_2_HD_IMG_2', 'http://placehold.it/1600x1000/ffff00/fff?text=Product+Image.jpg');
 	define('ROOMS_PLAN_1_SPOT_2_IMG_3', 'http://placehold.it/400x250/00ffff/fff?text=Product+Image.jpg');
 	define('ROOMS_PLAN_1_SPOT_2_HD_IMG_3', 'http://placehold.it/1600x1000/00ffff/fff?text=Product+Image.jpg');
?>